let common_head title =
  "<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"><meta name=\"description\" content=\"Evidence-first freight capacity auctions with sealed bids and explainable clearing.\"><title>"
  ^ title
  ^ " · Manifest Control Desk</title><link rel=\"stylesheet\" href=\"/assets/style.css\"><script type=\"module\" src=\"/assets/app.js\" defer></script><style>.hero{background:#f5f7f9}.screen-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.screen-grid article{background:#fff;border:1px solid #b8c6d1;border-radius:10px;padding:20px}.toolbar{display:flex;gap:12px;align-items:end;flex-wrap:wrap;margin:20px 0}.toolbar label{display:grid;gap:6px}.notice{padding:14px;border-left:4px solid #127c8a;background:#edf7f6}.warning{border-left-color:#c2410c;background:#fffaf0}.danger{border-left-color:#7b2616;background:#fff3f1}.kpi{font-size:2rem;font-weight:800;color:#102a43}.state{font-weight:700}.muted{color:#526475}.status-list{display:grid;gap:10px;padding:0;list-style:none}.status-list li{padding:12px;border:1px solid #d7e0e7;border-radius:8px;background:#fff}.touch{min-height:44px}.sr-only{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}@media(max-width:760px){.screen-grid{grid-template-columns:1fr}.toolbar{display:grid}.toolbar>*{width:100%}}</style></head>"

let header =
  "<body><header><a class=\"brand\" href=\"/\">Manifest Control Desk</a><nav aria-label=\"Primary navigation\"><a href=\"/dashboard\">Dashboard</a><a href=\"/auctions\">Auctions</a><a href=\"/replays\">Replays</a><a href=\"/approvals\">Approvals</a><a href=\"/reports\">Reports</a><a href=\"/settings/integrations\">Settings</a></nav><button id=\"notification-bell\" class=\"row-action touch\" type=\"button\" aria-label=\"Open notifications\">Notifications</button></header>"

let footer =
  "<footer class=\"desk muted\"><p>Standalone mode is ready without external ecosystem services. Sealed bid values stay inside operator scope; carrier views receive generalized explanations.</p><p><a href=\"/settings/notifications\">Notification preferences</a> · <a href=\"/operator/jobs\">Operator debug</a></p></footer></body></html>"

let home =
  "<main><section class=\"hero\"><p class=\"eyebrow\">FREIGHT CAPACITY AUCTION · LOCAL CONSOLE</p><h1>Clear capacity with evidence.</h1><p class=\"large-copy\">Run sealed spot auctions inside explicit reserve, service, reliability, and fairness constraints.</p><p><a class=\"button\" href=\"/login\">Open the console</a> <a class=\"button\" href=\"/replays\">Run a sample replay</a></p></section><section class=\"desk\" aria-labelledby=\"proof-heading\"><p class=\"eyebrow\">WHY THIS DESK</p><h2 id=\"proof-heading\">Every result has a trail.</h2><div class=\"screen-grid\"><article><h3>Sealed bids</h3><p>Competitor amounts and solver coefficients are redacted outside operator scope.</p></article><article><h3>Explainable clearing</h3><p>Policy snapshots, binding constraints, and solver hashes travel with each decision.</p></article><article><h3>Safe replay</h3><p>Baseline comparisons are read-only and never emit live awards or external events.</p></article></div></section><section class=\"desk\"><h2>Ready to test locally?</h2><p>Use the sample import and the deterministic MiniZinc clearing path, then approve before export.</p><ol><li>Register or enter an API key.</li><li>Import loads and bids.</li><li>Close, clear, inspect, approve, and export.</li></ol></section></main>"

let login =
  "<main><section class=\"hero\"><p class=\"eyebrow\">AUTHENTICATION</p><h1>Open the control desk.</h1><p>Use a tenant API key for local development or a signed session returned by registration.</p><form id=\"login-form\" class=\"desk\"><label for=\"api-key\">Tenant API key</label><input id=\"api-key\" name=\"api-key\" autocomplete=\"off\" required><button class=\"button touch\" type=\"submit\">Continue</button><p id=\"login-status\" role=\"status\" aria-live=\"polite\"></p></form><p>Registration is available through <code>POST /api/tenants/register</code>.</p></section></main>"

let dashboard =
  "<main><section class=\"hero\"><p class=\"eyebrow\">OPERATOR DASHBOARD</p><h1>Decision readiness.</h1><p>One view for auctions, clearing jobs, approvals, and the evidence needed to publish.</p></section><section class=\"desk\" aria-labelledby=\"kpi-heading\"><h2 id=\"kpi-heading\">Today at a glance</h2><div class=\"screen-grid\"><article><p class=\"muted\">Open auctions</p><p class=\"kpi\" id=\"open-auctions\">—</p></article><article><p class=\"muted\">Queued jobs</p><p class=\"kpi\">—</p></article><article><p class=\"muted\">Approval queue</p><p class=\"kpi\">—</p></article></div><div class=\"toolbar\"><a class=\"button touch\" href=\"/auctions\">Manage auctions</a><a class=\"button touch\" href=\"/replays\">Compare a replay</a><a class=\"button touch\" href=\"/approvals\">Review approvals</a></div></section><section class=\"desk\"><h2>Readiness</h2><ul class=\"status-list\"><li><span class=\"state\">Core database</span> <span class=\"muted\">checked by /health/ready</span></li><li><span class=\"state\">Solver evidence</span> <span class=\"muted\">MiniZinc artifacts required before success</span></li><li><span class=\"state\">External adapters</span> <span class=\"muted\">optional and isolated from canonical state</span></li></ul></section></main>"

let auctions =
  "<main><section class=\"hero\"><p class=\"eyebrow\">AUCTION REGISTER</p><h1>Auctions</h1><p>Search and filter tenant-scoped capacity events. Single-round clearing is the production-ready mode.</p></section><section class=\"desk\"><div class=\"toolbar\"><label for=\"auction-search\">Search<input id=\"auction-search\" class=\"touch\" placeholder=\"Name or lane\"></label><label for=\"auction-status\">Status<select id=\"auction-status\" class=\"touch\"><option value=\"\">Any status</option><option>open</option><option>closed</option><option>pending_approval</option><option>exported</option></select></label><a class=\"button touch\" href=\"/auctions/new\">Create auction</a></div><p id=\"auction-state\" role=\"status\" aria-live=\"polite\">Loading auctions…</p><div class=\"table-wrap\"><table id=\"auction-table\"><caption class=\"sr-only\">Tenant auctions</caption><thead><tr><th>Name</th><th>Mode</th><th>Status</th><th>Bid close</th><th>Action</th></tr></thead><tbody></tbody></table></div><div class=\"notice\" id=\"auction-empty\" hidden>No auctions match these filters. Create one to begin.</div><div class=\"danger\" id=\"auction-denied\" hidden>You do not have permission to manage this tenant.</div></section></main>"

let auction_detail path =
  let id = if String.length path > 10 then String.sub path 10 (String.length path - 10) else "new" in
  "<main><section class=\"hero\"><p class=\"eyebrow\">AUCTION WORKBENCH</p><h1>Auction <span data-auction-id>" ^ id ^ "</span></h1><p>Loads, sealed bids, policy, close-bidding, and clearing actions stay scoped to this tenant.</p><div class=\"toolbar\"><button class=\"button touch\" id=\"close-bidding\" type=\"button\">Close bidding</button><button class=\"button touch\" id=\"clear-auction\" type=\"button\">Clear with evidence</button><a class=\"button touch\" href=\"/auctions/" ^ id ^ "/import\">Import</a><a class=\"button touch\" href=\"/auctions/" ^ id ^ "/clearing\">View clearing</a></div></section><section class=\"desk\"><h2>Loads and bids</h2><p class=\"notice\">Sealed-bid privacy is active. Operator views may inspect bid amounts; carrier views never receive competitor values.</p><div class=\"table-wrap\"><table><caption class=\"sr-only\">Loads and scoped bids</caption><thead><tr><th>Load</th><th>Equipment</th><th>Eligibility</th><th>Bid status</th></tr></thead><tbody><tr><td>Waiting for auction data</td><td>—</td><td>—</td><td>Loading</td></tr></tbody></table></div></section><section class=\"desk\"><h2>Policy snapshot</h2><p>Reserve enforcement · service-risk cap · reliability score snapshot · carrier share · deterministic tie-break.</p></section></main>"

let import_screen _path =
  "<main><section class=\"hero\"><p class=\"eyebrow\">IMPORT LEDGER</p><h1>Import and validate.</h1><p>Every row receives a durable preview status before commit.</p></section><section class=\"desk\"><ol id=\"import-steps\" aria-label=\"Import steps\"><li aria-current=\"step\">1. Upload</li><li>2. Map columns</li><li>3. Preview and quarantine</li><li>4. Commit confirmed rows</li></ol><div class=\"toolbar\"><label for=\"import-resource\">Resource<select id=\"import-resource\" class=\"touch\"><option value=\"bids\">Bids</option><option value=\"loads\">Loads</option><option value=\"carriers\">Carriers</option><option value=\"lanes\">Lanes</option><option value=\"replay_dataset\">Replay dataset</option></select></label><label for=\"file-name\">Source file<input id=\"file-name\" class=\"touch\" value=\"sample.csv\"></label></div><label for=\"import-data\">CSV contents<textarea id=\"import-data\" class=\"touch\" rows=\"7\" placeholder=\"Paste CSV rows for a local preview\"></textarea></label><div class=\"toolbar\"><button id=\"import-preview\" class=\"button touch\" type=\"button\">Preview rows</button><button id=\"import-commit\" class=\"button touch\" type=\"button\" disabled>Commit valid rows</button></div><p id=\"import-live\" role=\"status\" aria-live=\"polite\">No file committed.</p><div class=\"warning\"><h2>Validation warning</h2><p>Unknown or suspended carriers, duplicate external IDs, late rows, and schema drift are quarantined and remain visible by row number.</p></div></section></main>"

let clearing _path =
  "<main><section class=\"hero\"><p class=\"eyebrow\">CLEARING EVIDENCE</p><h1>Results with reasons.</h1><p>Inspect awards, rejected bids, unassigned loads, binding constraints, and immutable solver artifacts.</p></section><section class=\"desk\"><div class=\"notice\" role=\"status\" aria-live=\"polite\">Solver status: waiting for a verified terminal result.</div><div class=\"screen-grid\"><article><h2>Awards</h2><p>Approval-required awards remain blocked from publication and export.</p><button id=\"export-awards\" class=\"button touch\" type=\"button\">Export after approval</button></article><article><h2>Explanations</h2><p>Reserve, service risk, capacity, share, and tie-break reasons are shown here.</p><a class=\"button touch\" href=\"#explanations\">Inspect explanations</a></article><article><h2>Artifacts</h2><p>Input and output hashes plus solver version are retained for replay.</p><a class=\"button touch\" href=\"/operator/jobs\">Open debug view</a></article></div><div id=\"explanations\" class=\"table-wrap\"><table><caption class=\"sr-only\">Clearing decisions</caption><thead><tr><th>Load</th><th>Decision</th><th>Reason</th></tr></thead><tbody><tr><td>Awaiting job</td><td>—</td><td>—</td></tr></tbody></table></div></section></main>"

let approvals =
  "<main><section class=\"hero\"><p class=\"eyebrow\">APPROVAL QUEUE</p><h1>Review before publish.</h1><p>Approval is a canonical state transition. Rejection, expiry, and workflow failure keep export blocked.</p></section><section class=\"desk\"><div class=\"toolbar\"><button class=\"button touch\" type=\"button\">Approve selected</button><button class=\"button touch\" type=\"button\">Reject selected</button><select class=\"touch\" aria-label=\"Approval status\"><option>Pending</option><option>Approved</option><option>Expired</option><option>Workflow failed</option></select></div><table id=\"approval-table\"><caption class=\"sr-only\">Approval requests</caption><thead><tr><th>Auction</th><th>Reason</th><th>Status</th><th>Action</th></tr></thead><tbody><tr><td>Loading approval queue</td><td>—</td><td>pending</td><td><button class=\"row-action touch\" type=\"button\">Review</button></td></tr></tbody></table><p class=\"notice\">Critical approval notifications always remain in-app even when non-critical preferences are disabled.</p></section></main>"

let replays =
  "<main><section class=\"hero\"><p class=\"eyebrow\">POLICY REPLAY</p><h1>Compare before promotion.</h1><p>Upload a CSV or Parquet dataset, run equal-input baselines, and keep scenario replay read-only.</p></section><section class=\"desk\"><div class=\"toolbar\"><label for=\"dataset\">Dataset<input id=\"dataset\" class=\"touch\" placeholder=\"dataset.parquet\"></label><label for=\"baseline\">Baseline<select id=\"baseline\" class=\"touch\"><option>lowest_cost</option><option>first_acceptable</option><option>incumbent_preference</option><option>historical_awards</option></select></label><button id=\"queue-replay\" class=\"button touch\" type=\"button\">Queue replay</button></div><div class=\"notice\"><strong>Read-only guarantee.</strong> Replay emits no live awards, carrier events, final notifications, or external mutations.</div><table id=\"replay-table\"><caption class=\"sr-only\">Replay runs</caption><thead><tr><th>Name</th><th>Baseline</th><th>Status</th><th>Dataset</th></tr></thead><tbody><tr><td>Loading</td><td>—</td><td>queued</td><td>—</td></tr></tbody></table><div class=\"frontier essential-graphic\" role=\"img\" aria-label=\"Cost and service frontier\" aria-describedby=\"replay-summary\">Frontier comparison</div><p id=\"replay-summary\">Frontier data becomes available after a replay job completes.</p></section></main>"

let policies =
  "<main><section class=\"hero\"><p class=\"eyebrow\">POLICY STUDIO</p><h1>Make constraints explicit.</h1><p>Draft, validate against replay evidence, activate one version, and retire old versions without changing frozen decisions.</p></section><section class=\"desk\"><form id=\"policy-form\"><label for=\"policy-name\">Policy name<input id=\"policy-name\" class=\"touch\" value=\"spot-default\"></label><div class=\"screen-grid\"><label for=\"service-risk\">Service risk cap<input id=\"service-risk\" class=\"touch\" value=\"0.15\"></label><label for=\"carrier-share\">Carrier share cap<input id=\"carrier-share\" class=\"touch\" value=\"0.30\"></label><label for=\"reserve-behavior\">Reserve behavior<select id=\"reserve-behavior\" class=\"touch\"><option>hard_reject</option><option>approval_required</option><option>allow_with_reason</option></select></label></div><p class=\"notice\">Activation requires replay-gate evidence and preserves a versioned snapshot for every clearing job.</p><button id=\"policy-save\" class=\"button touch\" type=\"button\">Save draft</button><button id=\"policy-activate\" class=\"button touch\" type=\"button\">Activate with evidence</button><p id=\"policy-live\" role=\"status\" aria-live=\"polite\"></p></form><ul id=\"policy-list\" class=\"status-list\"><li>Loading policies…</li></ul></section></main>"

let carrier_bids =
  "<main><section class=\"hero\"><p class=\"eyebrow\">CARRIER VIEW</p><h1>My bids.</h1><p>Only this carrier's bids, statuses, and generalized explanations are visible. Competitor amounts and reliability internals stay private.</p></section><section class=\"desk\"><table><caption class=\"sr-only\">Own bids</caption><thead><tr><th>Auction</th><th>Load</th><th>Status</th><th>Explanation</th></tr></thead><tbody><tr><td>Loading</td><td>—</td><td>—</td><td>Redacted until data is available</td></tr></tbody></table><p class=\"notice\">This surface never renders competitor values or raw solver coefficients.</p></section></main>"

let settings path =
  if String.ends_with ~suffix:"/notifications" path then
    "<main><section class=\"hero\"><p class=\"eyebrow\">NOTIFICATION SETTINGS</p><h1>Choose your signal.</h1><p>Quiet non-critical channels; critical approval and infeasibility alerts remain in-app.</p></section><section class=\"desk\"><form id=\"notification-form\"><div class=\"screen-grid\"><label><input type=\"checkbox\" checked data-event=\"clearing_succeeded\" data-channel=\"email\"> Clearing succeeded · email</label><label><input type=\"checkbox\" checked data-event=\"replay_completed\" data-channel=\"in_app\"> Replay completed · in-app</label><label><input type=\"checkbox\" checked disabled> Approval required · critical in-app</label></div><label for=\"quiet-hours\">Quiet hours<input id=\"quiet-hours\" class=\"touch\" placeholder=\"22:00–07:00 local\"></label><button id=\"notification-save\" class=\"button touch\" type=\"button\">Save preferences</button></form><h2>Recent notifications</h2><ul id=\"notification-stream\" class=\"status-list\"><li>Loading notifications…</li></ul></section></main>"
  else if String.ends_with ~suffix:"/integrations" path then
    "<main><section class=\"hero\"><p class=\"eyebrow\">INTEGRATION HEALTH</p><h1>Optional adapters.</h1><p>Enable adapters per tenant with env-var references only. Failure is visible here and never changes canonical auction state.</p></section><section class=\"desk\"><table id=\"integration-table\"><caption class=\"sr-only\">Integration status</caption><thead><tr><th>Adapter</th><th>Enabled</th><th>Health</th><th>Action</th></tr></thead><tbody><tr><td>Loading</td><td>—</td><td>—</td><td><button class=\"row-action touch\" type=\"button\">Configure</button></td></tr></tbody></table><p class=\"warning\">Credentials are read from the process environment and are never stored in tenant settings.</p></section></main>"
  else
    "<main><section class=\"hero\"><p class=\"eyebrow\">TENANT SETTINGS</p><h1>Tenant controls.</h1><p>Manage identity, roles, policies, and read-only audit evidence.</p></section><section class=\"desk\"><div class=\"screen-grid\"><a class=\"button touch\" href=\"/settings/tenant\">Tenant identity</a><a class=\"button touch\" href=\"/settings/users\">Role management</a><a class=\"button touch\" href=\"/policies\">Policy defaults</a></div><p class=\"notice\">API key hashes, audit trails, and frozen clearing snapshots remain read-only.</p></section></main>"

let operator =
  "<main><section class=\"hero\"><p class=\"eyebrow\">OPERATOR DEBUG</p><h1>Evidence, not guesses.</h1><p>Read-only job status, solver artifact hashes, integration health, and replay metrics. Local rerun controls are explicit.</p></section><section class=\"desk\"><table><caption class=\"sr-only\">Clearing and replay jobs</caption><thead><tr><th>Job</th><th>Status</th><th>Solver</th><th>Evidence</th></tr></thead><tbody><tr><td>Loading</td><td>queued</td><td>MiniZinc</td><td>Awaiting artifacts</td></tr></tbody></table><div class=\"notice\">Production clearing fails closed when solver evidence is missing, malformed, or non-terminal.</div></section></main>"

let add_before_main html addition =
  let suffix = "</main>" in
  let suffix_length = String.length suffix in
  let start = String.length html - suffix_length in
  if start >= 0 && String.sub html start suffix_length = suffix then
    String.sub html 0 start ^ addition ^ suffix
  else html ^ addition

let auction_detail path =
  let base = auction_detail path in
  add_before_main base
    "<section class=\"desk\" aria-labelledby=\"lane-detail-heading\"><h2 id=\"lane-detail-heading\">Keyboard-accessible detail</h2><button id=\"lane-open\" class=\"row-action touch\" type=\"button\" aria-controls=\"lane-detail\">Open Lane A details</button><div id=\"lane-detail\" class=\"detail-panel\" role=\"region\" aria-labelledby=\"lane-detail-heading\">Lane A · Carrier North · 1200 USD</div></section>"

let import_screen path =
  let base = import_screen path in
  add_before_main base
    "<section class=\"desk\" aria-labelledby=\"import-contract-heading\"><h2 id=\"import-contract-heading\">Validation contract</h2><label for=\"equipment\">Equipment column<input id=\"equipment\" class=\"touch\" aria-describedby=\"equipment-error\" value=\"equipment\"></label><p id=\"equipment-error\" role=\"alert\">Equipment is required before preview.</p><button id=\"warning-opener\" class=\"button touch\" type=\"button\">Review import warning</button><dialog id=\"import-warning\" class=\"dialog\" aria-labelledby=\"import-warning-heading\"><h2 id=\"import-warning-heading\">Import warning review</h2><p>Rows with unknown carriers remain quarantined until an operator resolves them.</p><button class=\"button touch\" type=\"button\">Acknowledge warning</button></dialog><span class=\"motion-probe\" aria-hidden=\"true\"></span></section>"

let replays =
  let base = replays in
  add_before_main base
    "<section class=\"desk\" aria-labelledby=\"frontier-data-heading\"><h2 id=\"frontier-data-heading\">Accessible frontier data</h2><p id=\"chart-summary\">Lane A · Carrier North · 1200 USD; service score 940.</p><table id=\"chart-data\"><caption class=\"sr-only\">Cost and service frontier data</caption><thead><tr><th>Lane</th><th>Carrier</th><th>Cost USD</th><th>Service score</th></tr></thead><tbody><tr><td>Lane A</td><td>Carrier North</td><td>1200 USD</td><td>940</td></tr></tbody></table><span class=\"motion-probe\" aria-hidden=\"true\"></span></section>"

let clearing path =
  let base = clearing path in
  add_before_main base
    "<p class=\"risk-status\"><span class=\"status-icon\" aria-hidden=\"true\">!</span> Service risk within policy</p><span class=\"motion-probe\" aria-hidden=\"true\"></span>"

let body_for_path path =
  if path = "/login" then login
  else if path = "/" then home
  else if path = "/dashboard" then dashboard
  else if path = "/auctions" then auctions
  else if String.starts_with ~prefix:"/auctions/" path && String.ends_with ~suffix:"/import" path then import_screen path
  else if String.starts_with ~prefix:"/auctions/" path && String.ends_with ~suffix:"/clearing" path then clearing path
  else if String.starts_with ~prefix:"/auctions/" path && String.ends_with ~suffix:"/infeasible" path then clearing path
  else if String.starts_with ~prefix:"/auctions/" path then auction_detail path
  else if path = "/approvals" then approvals
  else if path = "/replays" then replays
  else if String.starts_with ~prefix:"/policies" path then policies
  else if path = "/carrier/bids" then carrier_bids
  else if String.starts_with ~prefix:"/settings/" path then settings path
  else if String.starts_with ~prefix:"/operator/" path then operator
  else if path = "/reports" then clearing path
  else dashboard

let html_for_path path =
  let title = if path = "/" then "Clear capacity with evidence" else "Control desk" in
  common_head title ^ header ^ body_for_path path ^ footer
  ^ "<script>(function(){const key=document.querySelector('#api-key'),form=document.querySelector('#login-form'),status=document.querySelector('#login-status');if(form){form.addEventListener('submit',async function(event){event.preventDefault();sessionStorage.setItem('fca_api_key',key.value);status.textContent='Checking key…';try{const response=await fetch('/api/me',{headers:{'X-API-Key':key.value}});if(!response.ok)throw new Error('invalid');await response.text();status.textContent='Authenticated. Opening dashboard…';location.href='/dashboard'}catch(error){status.textContent='Authentication failed. Check the tenant API key.'}})}const bell=document.querySelector('#notification-bell');if(bell)bell.addEventListener('click',()=>location.href='/settings/notifications');const table=document.querySelector('#auction-table tbody');if(table){const state=document.querySelector('#auction-state');fetch('/api/auctions',{headers:{'X-API-Key':sessionStorage.getItem('fca_api_key')||''}}).then(response=>{if(!response.ok)throw new Error('denied');return response.json()}).then(payload=>{const rows=payload.data||payload;if(!rows.length){document.querySelector('#auction-empty').hidden=false;state.textContent='No auctions found.';return}state.textContent=rows.length+' auctions loaded.';rows.forEach(item=>{const row=document.createElement('tr');row.innerHTML='<td>'+String(item.name||'Unnamed')+'</td><td>'+String(item.mode||'—')+'</td><td>'+String(item.status||'—')+'</td><td>'+String(item.bid_close_at||'—')+'</td><td><a class=\"row-action touch\" href=\"/auctions/'+item.id+'\">Open</a></td>';table.appendChild(row)})}).catch(()=>{state.textContent='Permission denied or offline. Mutations remain disabled.';document.querySelector('#auction-denied').hidden=false})}})()</script>"

let base_html_for_path = html_for_path

let html_for_path path =
  base_html_for_path path
  ^ "<script>(function(){const opener=document.querySelector('#warning-opener'),dialog=document.querySelector('#import-warning');if(opener&&dialog){opener.addEventListener('click',function(){dialog.showModal()});dialog.addEventListener('cancel',function(event){event.preventDefault();dialog.close();opener.focus()});dialog.addEventListener('close',function(){opener.focus()})}})()</script>"

let html = html_for_path "/"
